#!/bin/bash -eo pipefail

USAGE="USAGE: extract <week number> <target folder>"

RED='\033[1;31m'
GREEN='\033[1;32m'
RESET='\033[0m' # No Color

printError() {
  echo -e "${RED}$@${RESET}"
}

printGreen()
{
  echo -e "${GREEN}$@${RESET}"
}

if [ $# -ne 2 ];then
  printError $USAGE
  exit 1
fi

WEEK_NR=$1
CODE_FOLDER="week_$1"
CODE_ZIP_FILE=${CODE_FOLDER}.zip
TARGET_FOLDER=$2

# Test if code folder exists
if [ ! -d $CODE_FOLDER ];then
  printError "No code found for $CODE_FOLDER"
  exit 1
fi
# Test if target folder exists
if [ ! -d $TARGET_FOLDER ];then
  printError "No such folder: $TARGET_FOLDER"
  exit 1
fi

TMP_FOLDER=$(mktemp -d)

cp -r $CODE_FOLDER $TMP_FOLDER
(
 cd $TMP_FOLDER
 find ${CODE_FOLDER} -name target -o \
                     -name .bloop -o \
                     -name .metals -o \
                     -name .idea -o \
                     -name .vscode \
                     -type d | xargs rm -rf
 find ${CODE_FOLDER} -name .DS_Store -type f | xargs rm -f
 zip -r ${CODE_ZIP_FILE} ${CODE_FOLDER} 2>&1 > /dev/null
 mv ${CODE_FOLDER}.zip ${TARGET_FOLDER}
)
 
printGreen "Extracted code for ${CODE_FOLDER} to ${TARGET_FOLDER}/${CODE_ZIP_FILE}"

# Clean-up
trap "rm -rf ${TMP_FOLDER}; exit 0" 0 
